"""
Phase 2 — DOCUMENTED
Creates JIRA issues/<task_id>/README.md and linked docs.
"""
import os
import logging
from datetime import datetime
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.workflow import Workflow
from app.core.config import get_settings
from app.integrations.jira_client import JiraClient

logger = logging.getLogger(__name__)
settings = get_settings()


class DocsGeneratorService:
    async def run(self, workflow: Workflow, db: AsyncSession) -> tuple[str, dict]:
        logger.info(f"[DOCUMENTED] Generating docs for {workflow.task_id}")

        task_dir = os.path.join(settings.jira_issues_path, workflow.task_id)
        os.makedirs(task_dir, exist_ok=True)

        # ── Write README.md ────────────────────────
        readme_path = os.path.join(task_dir, "README.md")
        readme_content = _build_readme(workflow)
        with open(readme_path, "w") as f:
            f.write(readme_content)

        # ── Write test-cases.md ────────────────────
        test_cases_path = os.path.join(task_dir, "test-cases.md")
        with open(test_cases_path, "w") as f:
            f.write(_build_test_cases_template(workflow))

        # ── Write security-review.md ───────────────
        security_path = os.path.join(task_dir, "security-review.md")
        with open(security_path, "w") as f:
            f.write(_build_security_template(workflow))

        # ── Update Jira issue ──────────────────────
        jira_url = None
        try:
            client = JiraClient()
            jira_url = await client.update_issue_status(workflow.task_id, "In Progress")
        except Exception as e:
            logger.warning(f"Jira update skipped: {e}")

        # Save jira_url to workflow
        if jira_url:
            workflow.jira_url = jira_url
            await db.commit()

        output_lines = [
            f"Documentation generated for {workflow.task_id}",
            f"  📁 JIRA issues/{workflow.task_id}/README.md",
            f"  📁 JIRA issues/{workflow.task_id}/test-cases.md",
            f"  📁 JIRA issues/{workflow.task_id}/security-review.md",
        ]
        if jira_url:
            output_lines.append(f"  🔗 Jira: {jira_url}")

        artifacts = {
            "README.md": f"JIRA issues/{workflow.task_id}/README.md",
            "test-cases.md": f"JIRA issues/{workflow.task_id}/test-cases.md",
            "security-review.md": f"JIRA issues/{workflow.task_id}/security-review.md",
        }

        return "\n".join(output_lines), artifacts


def _build_readme(workflow: Workflow) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return f"""# {workflow.task_id} — {workflow.title}

**Generated by FlowGuard** on {now}

## Summary
{workflow.description or "_No description provided._"}

## Target Application
`{workflow.target_app}`

## Workflow Run
- ID: `{workflow.id}`
- Status: `{workflow.status}`
- Started: {workflow.created_at.strftime("%Y-%m-%d %H:%M UTC") if workflow.created_at else "—"}

## FlowGuard 7-Phase Checklist
- [ ] Phase 1: Impact Analysis
- [ ] Phase 2: Documentation (this file)
- [ ] Phase 3: Security Review
- [ ] Phase 4: E2E Testing (Playwright)
- [ ] Phase 5: Git Commit
- [ ] Phase 6: Pull Request
- [ ] Phase 7: Deployment

## Files
| File | Purpose |
|------|---------|
| `README.md` | Task overview and checklist |
| `test-cases.md` | Playwright test cases |
| `security-review.md` | Security and browser compat findings |

## Links
- Jira: {workflow.jira_url or "_(pending)_"}
- GitHub PR: {workflow.github_pr_url or "_(pending)_"}
- Branch: `{workflow.github_branch or "_(pending)_"}`

---
_This document is auto-maintained by FlowGuard. Do not edit manually._
"""


def _build_test_cases_template(workflow: Workflow) -> str:
    return f"""# Test Cases — {workflow.task_id}

**Generated by FlowGuard**

## Overview
Test cases for: {workflow.title}
Application: `{workflow.target_app}`

## Test Scenarios

### TC-001: Happy Path
- **Given** the user navigates to the feature
- **When** they perform the primary action
- **Then** the expected result occurs

### TC-002: Edge Case — Empty Input
- **Given** the user provides no input
- **When** they submit the form
- **Then** validation error is displayed

### TC-003: Error Handling
- **Given** an API failure occurs
- **When** the user performs an action
- **Then** a user-friendly error message is shown

### TC-004: Browser Compatibility
- **Given** the feature is opened in Chrome, Firefox, Safari
- **When** all interactions are performed
- **Then** behavior is consistent across all browsers

### TC-005: Authentication Gate
- **Given** an unauthenticated user
- **When** they access a protected route
- **Then** they are redirected to login

## Playwright Test File
See: `test-reports/{workflow.task_id}/`

---
_Auto-generated by FlowGuard Phase 2 (DOCUMENTED)_
"""


def _build_security_template(workflow: Workflow) -> str:
    return f"""# Security Review — {workflow.task_id}

**Generated by FlowGuard Phase 3 (SECURITY)**

## Checklist

### Authentication & Authorisation
- [ ] All routes protected with JWT
- [ ] Role checks enforced (admin/developer)
- [ ] No sensitive data in URL params
- [ ] Token expiry handled

### Input Validation
- [ ] All user inputs sanitised
- [ ] SQL injection prevention verified
- [ ] XSS prevention verified
- [ ] CSRF protection enabled

### Data Security
- [ ] No secrets in frontend code
- [ ] API keys not exposed in logs
- [ ] HTTPS enforced
- [ ] CORS configured correctly

### Browser Compatibility
- [ ] Chrome (latest)
- [ ] Firefox (latest)
- [ ] Safari (latest)
- [ ] Edge (latest)

## Findings
_(populated by automated security scan)_

## Status
- [ ] PASS
- [ ] WARN — review required
- [ ] FAIL — blocked, admin approval needed

---
_Auto-generated by FlowGuard Phase 2 (DOCUMENTED)_
"""
